# Generated by Django 4.2.3 on 2023-07-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='text',
            new_name='title',
        ),
    ]
