# Generated by Django 4.2.3 on 2023-07-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_settings_options_rename_text_settings_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='color_back',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='settings',
            name='color_text',
            field=models.CharField(max_length=7),
        ),
    ]
